# Generated by Django 3.2.9 on 2022-01-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rodzaj',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prywatne'), (1, 'zawodowe'), (2, 'programowanie')], default=0),
        ),
    ]
