# Generated by Django 3.2.9 on 2021-12-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': 'seriale', 'verbose_name_plural': 'seriale'},
        ),
        migrations.AlterUniqueTogether(
            name='serial',
            unique_together={('title', 'rok_produkcji')},
        ),
        migrations.RemoveField(
            model_name='serial',
            name='czas_trwania',
        ),
    ]
