# Generated by Django 3.2.9 on 2021-12-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0002_auto_20211201_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='film/images/%Y/%m/%d/'),
        ),
    ]
