# Generated by Django 3.2.9 on 2021-12-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0003_alter_serial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='image',
        ),
    ]
