# Generated by Django 3.2.9 on 2021-12-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'verbose_name': 'książka', 'verbose_name_plural': 'książki'},
        ),
        migrations.RenameField(
            model_name='ksiazka',
            old_name='data_obejrzenia',
            new_name='data_przeczytania',
        ),
        migrations.RenameField(
            model_name='ksiazka',
            old_name='rok_produkcji',
            new_name='rok_wydania',
        ),
        migrations.AlterUniqueTogether(
            name='ksiazka',
            unique_together={('title', 'rok_wydania')},
        ),
    ]
