# Generated by Django 3.2.9 on 2021-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_film_data_obejrzenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='gdzie_obejzano',
        ),
        migrations.AddField(
            model_name='film',
            name='gdzie_obejrzano',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Netflix'), (1, 'Apple'), (2, 'Amazon'), (3, 'Kino'), (4, 'Canal +'), (5, 'HBO'), (6, 'YouTube'), (7, 'TV'), (8, 'Inne')], default=8),
        ),
    ]
