# Generated by Django 3.2.9 on 2021-12-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_remove_film_czas_trwania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gdzie_obejrzano',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Netflix'), (1, 'Apple'), (2, 'Amazon'), (3, 'Kino'), (4, 'Canal +'), (5, 'HBO'), (6, 'YouTube'), (7, 'TV'), (8, 'Player.pl'), (9, 'Inne')], default=8),
        ),
    ]
